### PR TITLE
Changed the startup animation

### PR DESCRIPTION
**Pull request by ef1500**
Load

Was previously a pull request [here](https://github.com/manga-download/hakuneko/pull/3231).

### CODE REVIEW

**Comment by Sheepux** [comment]
Feature lost: 
- Button to close the loader, because it's currently not doing anything 😄 

Also i'm not fond of externalising CSS when there is no plan to reuse it but that might be a personal taste.

**Comment by ronny1982** [comment]
I think it is a good idea to embed the CSS styles into the HTML file, so there is just one request to show the splash instead of two

**Review by Sheepux — CHANGES_REQUESTED** [review]
two small improvements identified

**Comment by Sheepux** [comment]
Merged with a custom implementation.
Changed a bit the colors to the red one.
Final result below. It's nice !
hakuneko-loading2

**Pull request closed without merging**
